.TH "C:/Users/Maksim/Desktop/homework Directory Reference" 3 "Tue Jul 23 2019" "Version 1.1" "solve_square_equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Maksim/Desktop/homework Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBsolve_square_equation\fP"
.br
.in -1c
