.TH "main_module" 3 "Wed Jul 24 2019" "Version 1.2" "solve_square_equation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_module \- This is main module this is the module which contains all working functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBsolve square function module\fP"
.br
.RI "This function solving square equation\&. "
.ti -1c
.RI "\fBside module\fP"
.br
.RI "This function get's coefficients from wrote equation\&. "
.ti -1c
.RI "\fBin program module\fP"
.br
.RI "Main function\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is main module this is the module which contains all working functions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for solve_square_equation from the source code\&.
